workflow:
  name: '$PROJECT1_PIPELINE_NAME'
  rules:
    - if: '$BRANCH != "release" && $CI_PIPELINE_SOURCE == "web"'
      variables:
        PROJECT1_PIPELINE_NAME: 'Feature $BRANCH pipeline'
    - if: '$BRANCH == "release" && $CI_PIPELINE_SOURCE == "web"'
      variables:
        PROJECT1_PIPELINE_NAME: 'Release pipeline'

stages:
  - verify
  - prepare
  - generate-sdk
  - test
  - publish

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  JAVA_SDR_REPO_URL: "https://github.com/moysklad/java-remap-sdk-1.2.git"
  PHP_SDR_REPO_URL: "https://github.com/moysklad/php-remap-1.2-sdk.git"
  MAVEN_IMAGE_VERSION: "3.4-release"
  COMPOSER_IMAGE_VERSION: "2.7"
  API_HOST: "https://api-$API_NAMESPACE.testms-test.lognex.ru"

include:
  - local: gitlab/common.gitlab-ci.yml
  - local: gitlab/verify.gitlab-ci.yml
  - local: gitlab/prepare.gitlab-ci.yml
  - local: gitlab/generate-sdk.gitlab-ci.yml
  - local: gitlab/test.gitlab-ci.yml
  - local: gitlab/publish.gitlab-ci.yml
