stages:
  - verify
  - prepare
  - test
  - publish

variables:
  PHP_SDK_REPO_URL: "https://github.com/moysklad/php-remap-1.2-sdk.git"
  COMPOSER_IMAGE_VERSION: "2.7"

include:
  - local: gitlab/common.gitlab-ci.yml
  - local: gitlab/verify.gitlab-ci.yml
  - local: gitlab/prepare.gitlab-ci.yml
  - local: gitlab/test.gitlab-ci.yml