image: docker.lognex.ru/maven:1.4-release

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build:
  stage: build
  before_script:
    - apk add git
    - git clone https://github.com/moysklad/java-remap-sdk-1.2.git
    - cd java-remap-sdk-1.2
    - export TZ='Europe/Moscow'
  script:
    - if [ -z "BRANCH" ]; then
        export CI_REGISTRY=ossrh;
        export CI_REGISTRY_USER=${OSSRH_USER};
        export CI_REGISTRY_PASSWORD=${OSSRH_PASSWORD};
        echo "$GPG_SECRET_KEY" | gpg --import

        mvn $MAVEN_CLI_OPTS -Dusername=$GIT_USER -Dpassword=$GIT_PASSWORD release:prepare
        mvn release:perform
      else
        git checkout $BRANCH;
        mvn versions:set -DnewVersion=${BRANCH}-${CI_PIPELINE_ID}-SNAPSHOT -DgenerateBackupPoms=false;
        mvn $MAVEN_CLI_OPTS clean deploy;
      fi