invokerPackage: "ru.moysklad.remap_1_2.beta"
apiPackage: "ru.moysklad.remap_1_2.beta.api"
modelPackage: "ru.moysklad.remap_1_2.beta.model"
files:
  RequestOptions.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2.beta/api/RequestOptions.java
  PageOptions.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2.beta/api/PageOptions.java
  ListOptions.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2.beta/api/ListOptions.java
  AssortmentListOptions.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2.beta/api/AssortmentListOptions.java
  Filters.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2.beta/api/Filters.java
  Orders.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2.beta/api/Orders.java
  MetaEntity.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2/beta/model/MetaEntity.java
  IAttribute.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/ru/moysklad/remap_1_2/beta/model/IAttribute.java