post:
  operationId: createTaskNotesBatch
  tags:
    - Tasks
  summary: Создать комментарии Задачи
  description: Создание нескольких комментариев к Задаче.
  parameters:
    - $ref: '../../../components/parameters.yaml#/entityId'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
    - $ref: '../../../components/headers.yaml#/ContentTypeJson'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '../../../openapi.yaml#/components/schemas/TaskNote'
          minItems: 1
          maxItems: 1000
  responses:
    '200':
      description: Комментарии успешно созданы
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../../openapi.yaml#/components/schemas/BatchEntity'
    default:
      $ref: '../../../components/responses.yaml#/CommonError'
