post:
  operationId: createTaskMetadataStates
  tags:
    - Tasks
  summary: Создать или изменить типы задач
  description: Создание одного или нескольких типов задач
  parameters:
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
    - $ref: '../../../components/headers.yaml#/ContentTypeJson'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../openapi.yaml#/components/schemas/StatesUpsert'
  responses:
    '200':
      description: Тип задачи или список типов задач успешно обработаны
      content:
        application/json:
          schema:
            $ref: '../../../openapi.yaml#/components/schemas/StatesUpsertResult'
    default:
      $ref: '../../../components/responses.yaml#/CommonError'
