get:
  operationId: getTaskById
  tags:
    - Tasks
  summary: Получить задачу по ID
  description: Запрос задачи с указанным id
  parameters:
    - $ref: '../../../components/parameters.yaml#/entityId'
    - $ref: '../../../components/parameters.yaml#/expand'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
  responses:
    '200':
      description: Успешный запрос
      content:
        application/json:
          schema:
            $ref: '../../../openapi.yaml#/components/schemas/Task'
    default:
      $ref: '../../../components/responses.yaml#/CommonError'

put:
  operationId: updateTask
  tags:
    - Tasks
  summary: Обновить задачу
  description: Обновление задачи с указанным id
  parameters:
    - $ref: '../../../components/parameters.yaml#/entityId'
    - $ref: '../../../components/parameters.yaml#/expand'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
    - $ref: '../../../components/headers.yaml#/ContentTypeJson'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../openapi.yaml#/components/schemas/Task'
  responses:
    '200':
      description: Задача успешно обновлена
      content:
        application/json:
          schema:
            $ref: '../../../openapi.yaml#/components/schemas/Task'
    default:
      $ref: '../../../components/responses.yaml#/CommonError'

delete:
  operationId: deleteTask
  tags:
    - Tasks
  summary: Удалить задачу
  description: Удаление задачи с указанным id
  parameters:
    - $ref: '../../../components/parameters.yaml#/entityId'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
  responses:
    '200':
      description: Задача успешно удалена
    default:
      $ref: '../../../components/responses.yaml#/CommonError'
