get:
  operationId: getTasks
  tags:
    - Tasks
  summary: Получить список задач
  description: Запрос всех задач на данной учетной записи
  parameters:
    - $ref: '../../../components/parameters.yaml#/limit'
    - $ref: '../../../components/parameters.yaml#/offset'
    - $ref: '../../../components/parameters.yaml#/filter'
    - $ref: '../../../components/parameters.yaml#/expand'
    - $ref: '../../../components/parameters.yaml#/order'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
  responses:
    '200':
      description: Успешный запрос
      content:
        application/json:
          schema:
            $ref: '../../../openapi.yaml#/components/schemas/TaskList'
    default:
      $ref: '../../../components/responses.yaml#/CommonError'

post:
  operationId: createTask
  tags:
    - Tasks
  summary: Создать задачу
  description: Создание новой задачи
  parameters:
    - $ref: '../../../components/parameters.yaml#/expand'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
    - $ref: '../../../components/headers.yaml#/ContentTypeJson'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../openapi.yaml#/components/schemas/Task'
  responses:
    '200':
      description: Задача успешно создана
      content:
        application/json:
          schema:
            $ref: '../../../openapi.yaml#/components/schemas/Task'
    default:
      $ref: '../../../components/responses.yaml#/CommonError'
