get:
  tags:
    - ProductFolders
  summary: Получить список групп товаров
  description: Запрос всех групп товаров на данной учетной записи
  parameters:
    - $ref: '../../../components/parameters.yaml#/limit'
    - $ref: '../../../components/parameters.yaml#/offset'
    - $ref: '../../../components/parameters.yaml#/search'
    - $ref: '../../../components/parameters.yaml#/filter'
    - $ref: '../../../components/parameters.yaml#/expand'
    - $ref: '../../../components/parameters.yaml#/order'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
  responses:
    '200':
      description: Успешный запрос
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/dictionary/productFolderList.yaml'
    '400':
      $ref: '../../../components/responses.yaml#/BadRequest'
    '401':
      $ref: '../../../components/responses.yaml#/Unauthorized'
    '403':
      $ref: '../../../components/responses.yaml#/Forbidden'

post:
  tags:
    - ProductFolders
  summary: Создать группу товаров
  description: Создание новой группы товаров
  parameters:
    - $ref: '../../../components/parameters.yaml#/expand'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../components/schemas/dictionary/productFolder.yaml'
  responses:
    '200':
      description: Группа товаров успешно создана
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/dictionary/productFolder.yaml'
    '400':
      $ref: '../../../components/responses.yaml#/BadRequest'
    '401':
      $ref: '../../../components/responses.yaml#/Unauthorized'
    '403':
      $ref: '../../../components/responses.yaml#/Forbidden'