type: object
description: Решение
properties:
  meta:
    $ref: '../common/meta.yaml'
  id:
    type: string
    format: uuid
    description: ID решения
    readOnly: true
    example: "12a8b923-692c-11e6-8a84-bae500000054"
  account_id:
    type: string
    format: uuid
    description: ID учетной записи
    readOnly: true
  name:
    type: string
    description: Наименование решения
    readOnly: true
    example: "Иванов И. И."
  appUid:
    type: string
    description: Логин решения
    readOnly: true