type: object
description: Решение
properties:
  meta:
    $ref: '../common/meta.yaml'
  id:
    type: string
    format: uuid
    description: ID решения
    readOnly: true
  account_id:
    type: string
    format: uuid
    description: ID учетной записи
    readOnly: true
  name:
    type: string
    description: Наименование решения
    readOnly: true
  appUid:
    type: string
    description: Логин решения
    readOnly: true