type: object
x-entitytype-product: true
properties:
  meta:
    description: Метаданные Товара
    $ref: '../common/meta.yaml'
  id:
    type: string
    format: uuid
    description: ID товара
    readOnly: true
  accountId:
    type: string
    format: uuid
    description: ID учетной записи
    readOnly: true
  alcoholic:
    type: object
    description: Объект, содержащий поля алкогольной продукции
    properties:
      excise:
        type: boolean
        nullable: true
        description: Содержит акцизную марку
      type:
        type: integer
        minimum: 0
        nullable: true
        description: Код вида продукции
      strength:
        type: number
        minimum: 0
        nullable: true
        format: float
        description: Крепость
      volume:
        type: number
        minimum: 0
        nullable: true
        format: float
        description: Объём тары
  archived:
    type: boolean
    description: Добавлен ли товар в архив
  tobacco:
    type: boolean
    description: Признак товара, как табачной продукции
    readOnly: true
  name:
    type: string
    maxLength: 255
    description: Наименование товара
    example: "Товар 1"
  code:
    type: string
    maxLength: 255
    description: Код товара
  externalCode:
    type: string
    maxLength: 255
    description: Внешний код товара
  pathName:
    type: string
    description: Наименование группы, в которую входит товар
    readOnly: true
  article:
    type: string
    maxLength: 255
    description: Артикул
  description:
    type: string
    maxLength: 4096
    nullable: true
    description: Описание товара
  vat:
    type: integer
    minimum: 0
    maximum: 99
    description: НДС %
  vatEnabled:
    type: boolean
    description: Включен ли НДС для товара
  useParentVat:
    type: boolean
    description: Используется ли ставка НДС родительской группы
  effectiveVat:
    type: integer
    description: Реальный НДС %
    readOnly: true
  effectiveVatEnabled:
    type: boolean
    description: Дополнительный признак для определения разграничения реального НДС
    readOnly: true
  discountProhibited:
    type: boolean
    description: Признак запрета скидок
  variantsCount:
    type: integer
    description: Количество модификаций у данного товара
    readOnly: true
  isSerialTrackable:
    type: boolean
    description: Учет по серийным номерам
  shared:
    type: boolean
    description: Общий доступ
  group:
    description: Метаданные отдела сотрудника
    $ref: '../../../openapi.yaml#/components/schemas/Group'
  owner:
    description: Метаданные владельца (Сотрудника)
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/Owner'
  updated:
    type: string
    format: date-time
    description: Момент последнего обновления сущности
    readOnly: true
  weight:
    type: number
    format: float
    minimum: 0
    description: Вес
  volume:
    type: number
    format: float
    minimum: 0
    description: Объем
  buyPrice:
    description: Закупочная цена
    $ref: '../../../openapi.yaml#/components/schemas/BuyPrice'
  salePrices:
    type: array
    description: Цены продажи
    items:
      $ref: '../../../openapi.yaml#/components/schemas/SalePrice'
  supplier:
    description: Метаданные контрагента-поставщика
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/Counterparty'
  country:
    description: Метаданные Страны
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/Country'
  uom:
    description: Метаданные единиц измерения
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/Uom'
  productFolder:
    description: Метаданные группы Товара
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/ProductFolder'
  images:
    description: Массив изображений
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/ImageList'
  files:
    description: Метаданные массива Файлов
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/FileList'
  barcodes:
    type: array
    description: Штрихкоды товара
    items:
      $ref: '../../../openapi.yaml#/components/schemas/Barcode'
  packs:
    type: array
    description: Упаковки товара
    items:
      $ref: '../../../openapi.yaml#/components/schemas/Pack'
  trackingType:
    type: string
    description: Тип маркируемой продукции. Допустимые значения перечислены в константах класса
  tnved:
    type: string
    maxLength: 255
    description: Код ТН ВЭД
  paymentItemType:
    type: string
    enum:
      - GOOD
      - EXCISABLE_GOOD
      - COMPOUND_PAYMENT_ITEM
      - ANOTHER_PAYMENT_ITEM
    description: Признак предмета расчета
  taxSystem:
    type: string
    enum:
      - GENERAL_TAX_SYSTEM
      - SIMPLIFIED_TAX_SYSTEM_INCOME
      - SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME
      - UNIFIED_AGRICULTURAL_TAX
      - PRESUMPTIVE_TAX_SYSTEM
      - PATENT_BASED
      - TAX_SYSTEM_SAME_AS_GROUP
    description: Код системы налогообложения
  attributes:
    type: array
    description: Дополнительные поля
    items:
      $ref: '../../../openapi.yaml#/components/schemas/AttributeAbstract'
  minimumBalance:
    type: number
    format: float
    description: Неснижаемый остаток (устаревшее)
    deprecated: true
  minimumStock:
    description: Неснижаемый остаток
    nullable: true
    oneOf:
      - $ref: '../../../openapi.yaml#/components/schemas/MinimumStockAbstract'
  minPrice:
    description: Минимальная цена
    $ref: '../../../openapi.yaml#/components/schemas/MinPrice'
  weighed:
    type: boolean
    description: Поле, показывающее является ли товар весовым
  onTap:
    type: boolean
    description: Поле, показывающее является ли товар разливным
  partialDisposal:
    type: boolean
    description: Управление состоянием частичного выбытия маркированного товара
  things:
    type: array
    description: Серийные номера
    readOnly: true
    items:
      type: string
  syncId:
    type: string
    format: uuid
    description: ID синхронизации
  ppeType:
    type: string
    description: Код вида номенклатурной классификации медицинских средств индивидуальной защиты. Допустимые значения перечислены в константах класса