type: object
description: Производственное задание
properties:
  meta:
    description: Метаданные Производственного задания
    $ref: '../common/meta.yaml'
  id:
    type: string
    format: uuid
    description: ID Производственного задания
    readOnly: true
  accountId:
    type: string
    format: uuid
    description: ID учетной записи
    readOnly: true
  name:
    type: string
    maxLength: 255
    description: Наименование Производственного задания
  code:
    type: string
    maxLength: 255
    description: Код Производственного задания
  externalCode:
    type: string
    maxLength: 255
    description: Внешний код Производственного задания
  syncId:
    type: string
    format: uuid
    description: ID синхронизации
  description:
    type: string
    maxLength: 4096
    nullable: true
    description: Комментарий Производственного задания
  created:
    type: string
    description: Дата создания
    readOnly: true
  deleted:
    type: string
    description: Момент последнего удаления Производственного задания
    readOnly: true
  updated:
    type: string
    description: Момент последнего обновления Производственного задания
    readOnly: true
  moment:
    type: string
    description: Дата документа
