# Mirror Openapi specification to Remote Repository
#
# Этот файл содержит job'у для пуша измененной openapi спецификации в удалённый репозиторий.
# Job'а выполняется только при merge в master ветку.

# Push OpenApi Specification to GitHub
mirror-to-github:
  image: docker.infra.lognex/docker-openapitools:1.1-release
  stage: mirror
  before_script:
    - git config --global user.name "$GIT_USER"
    - git config --global user.email "$GIT_MAIL"
  script:
    - git clone $CI_REPOSITORY_URL temp_dir && cd temp_dir
    - git remote add github https://$GIT_PASSWORD@github.com/moysklad/api-remap-1.2-openapi-specification.git
    - git checkout $CI_COMMIT_REF_NAME
    - |
      # удаляем ненужные файлы
      if [ -d "gitlab" ]; then
        echo "Removing gitlab directory..."
        rm -rf gitlab
      fi
      
      if [ -f ".gitlab-ci.yml" ]; then
        echo "Removing gitlab-ci.yml..."
        rm -rf .gitlab-ci.yml
      fi

      # создаем новый корневой commit
      git checkout --orphan temp-branch
      git add -A
      git commit -m "Mirror to GitHub without GitLab-specific files"
      
      # Удаляем старую ветку и переименовываем новую
      git branch -D $CI_COMMIT_REF_NAME
      git branch -m $CI_COMMIT_REF_NAME
      
      git push github $CI_COMMIT_REF_NAME --force --no-verify
      echo "Successfully mirrored to GitHub without GitLab-specific files"
  variables:
    GIT_STRATEGY: clone