.common-java:
  image: docker.infra.lognex/maven:${MAVEN_IMAGE_VERSION}
  cache:
    paths:
      - .m2/repository/

.common-php:
  image: composer:${COMPOSER_IMAGE_VERSION}
  cache:
    key: composer-cache
    paths:
      - /tmp/composer/cache
  variables:
    COMPOSER_CACHE_DIR: "/tmp/composer/cache"

.common-generate-php-sdk:
  image: node:18-alpine
  stage: generate-sdk
  cache:
    key: npm-cache
    paths:
      - node_modules/
  before_script:
    - apk add --no-cache git rsync
    - git config --global user.name "sdk-bot"
    - git config --global user.email "sdk-bot@users.noreply.github.com"
  variables:
    SDK_BRANCH: $CI_COMMIT_REF_NAME
    SDK_REPO: moysklad/php-remap-1.2-sdk1
    SDK_REPO_URL: https://github.com/moysklad/php-remap-1.2-sdk.git
