test-java-sdk:
  extends: .common-java
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  needs:
    - prepare-java-sdk
  script:
    - cd java-remap-sdk-1.2
    - mvn -V -B -nsu -T 6 clean test
  artifacts:
    paths:
      - java-remap-sdk-1.2/
    expire_in: 2 hour


test-php-sdk:
  extends: .common-php
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  needs:
    - prepare-php-sdk
  script:
    - cd php-remap-1.2-sdk
    - vendor/bin/phpunit --colors=never ./test
  artifacts:
    paths:
      - php-remap-1.2-sdk/
    expire_in: 2 hour
