type: object
required:
  - context
  - meta
  - rows
properties:
  context:
    description: Метаданные о сотруднике, выполнившем запрос
    $ref: '../common/context.yaml'
  meta:
    description: Метаданные о выдаче
    $ref: '../common/metaList.yaml'
  rows:
    type: array
    description: Массив товаров
    items:
      $ref: '../../../openapi.yaml#/components/schemas/Product'