delete:
  operationId: deleteProductFile
  tags:
    - Products
  summary: Удалить файл товара
  description: Удаление Файла Товара
  parameters:
    - $ref: '../../../components/parameters.yaml#/entityId'
    - name: fileId
      in: path
      required: true
      description: ID файла
      schema:
        type: string
        format: uuid
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
  responses:
    '200':
      description: Файл успешно удалён
    default:
      $ref: '../../../components/responses.yaml#/Base'
    
    
    
