post:
  operationId: deleteProductStoreBalances
  tags:
    - Products
  summary: Массовое удаление НСО товара по складам
  description: Массовое удаление Неснижаемых остатков Товара по складам.
  parameters:
    - $ref: '../../../components/parameters.yaml#/entityId'
    - $ref: '../../../components/headers.yaml#/AcceptHeader'
    - $ref: '../../../components/headers.yaml#/AcceptEncoding'
    - $ref: '../../../components/headers.yaml#/ContentTypeJson'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            properties:
              meta:
                $ref: '../../../components/schemas/common/meta.yaml'
        example:
          - meta:
              href: "https://api.moysklad.ru/api/remap/1.2/entity/product/3e1c03bb-684f-11ee-ac12-000c000000b0/storebalances/7fce2da5-684d-11ee-ac12-000c000000a2"
              type: "minimumstock"
              mediaType: "application/json"
  responses:
    '200':
      description: НСО успешно удалены
    '400':
      $ref: '../../../components/responses.yaml#/BadRequest'
    '401':
      $ref: '../../../components/responses.yaml#/Unauthorized'
    '403':
      $ref: '../../../components/responses.yaml#/Forbidden'
    '404':
      $ref: '../../../components/responses.yaml#/NotFound'
    '413':
      $ref: '../../../components/responses.yaml#/PayloadTooLarge'
    '415':
      $ref: '../../../components/responses.yaml#/UnsupportedMediaType'
