name: Generate SDK

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout specification repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Validate OpenAPI specification
      run: npm run validate

    - name: Generate PHP SDK
      run: npm run generate-php

    - name: Setup Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Create SDK branch
      run: |
        SDK_BRANCH="sdk-$(date +%Y%m%d-%H%M%S)"
        echo "SDK_BRANCH=$SDK_BRANCH" >> $GITHUB_ENV
        git checkout -b $SDK_BRANCH

    - name: Commit generated SDK
      run: |
        git add clients/php/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generated PHP SDK from OpenAPI specification"
        fi

    - name: Push SDK branch
      run: |
        git push origin $SDK_BRANCH

    - name: Create SDK repository branch
      run: |
        SDK_REPO="moysklad/php-remap-1.2-sdk"
        SDK_BRANCH="${{ env.SDK_BRANCH }}"
        
        # Clone SDK repository
        git clone https://github.com/$SDK_REPO.git sdk-repo
        cd sdk-repo
        
        # Create and checkout new branch
        git checkout -b $SDK_BRANCH
        
        # Copy generated files
        cp -r ../clients/php/* .
        
        # Add and commit changes
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit in SDK repository"
        else
          git commit -m "Update SDK from specification repository"
          git push origin $SDK_BRANCH
          
          # Create pull request
          gh pr create \
            --title "Auto-generated SDK update" \
            --body "This PR contains auto-generated SDK updates from the OpenAPI specification." \
            --base main \
            --head $SDK_BRANCH
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
